name: Makefile CI

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    name: Build and Test


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      
      - name: Install Dependencies Ubuntu
        run: |
          sudo apt-get update
          sudo apt install -y gfortran
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran 100
    
        
      - name: Build and Test Linux
        run: |
            which gfortran
            gfortran --version
            ./buildtorus debug=yes
        
